routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role']], function () {

    Route::get('/', 'HomeController@admin');

    Route::get('/news/search', 'Admin\UserController@search');

    Route::get('/news/findCategory', 'Admin\UserController@findCategory');

/*<<<<<<< HEAD
    Route::get('/news/like', 'Admin\NewsController@likeNews')->name('likeNews');
    Route::get('/news/dislike', 'Admin\NewsController@disLikeNews')->name('disLikeNews');

=======
*/
    Route::get('/news/like/{id}', 'Admin\NewsController@likeNews')->name('likeNews');
    Route::get('/news/dislike/{id}', 'Admin\NewsController@disLikeNews')->name('disLikeNews');
    Route::get('/news/commentNews/{id}', 'Admin\NewsController@commentNews');
    //Route::post('comment/{news}','CommentController@store')->name('comment.store');
//>>>>>>> origin/new_branch

    Route::post('/news/comment/{news}','CommentController@store')->name('comment.store');
    Route::delete('/news/deleteComment/{id}','CommentController@delete')->name('comment.delete');

//  News
    Route::resource('/news', 'Admin\NewsController');

//    Category
    Route::resource('/category', 'Admin\CategoryController');

    Route::get('/user', 'Admin\UserController@registered');

    Route::get('/user-edit/{id}', 'Admin\UserController@registeredit');

    Route::put('/user-update/{id}', 'Admin\UserController@registerupdate');


    Route::get('/ip', 'Admin\UserController@index');


    Route::post('/news/ffmpeg/{id}', 'Admin\UserController@ffmpeg');
    Route::delete('/news/ffmpeg/{id}','Admin\UserController@ffmpeg');

    Route::get('/feedback', 'Admin\UserController@feedbackindex');
    Route::post('/feedback/send', 'Admin\UserController@send');



});
/*Route::get('/test', function () {
    $img = \Intervention\Image\Facades\Image::make(public_path() . '/new1574168086.png')->blur(80);

    return $img->response('jpg');
});*/
/*Route::group(['prefix'=>'admin','middleware'=>'auth'], function (){
    Route::get('/', function (){
        return "i am in user panel";
    });
});       */

resources/views/admin/category-add.blade.php
@extends('layouts.app')

@section('title', 'Category add')

@section('page-name', 'Category add page')

@section('content')
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <form action="{{ route('category.store') }}" method="post" role="form">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" value="{{ old('name') }}" id="name" class="form-control" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Add category</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/category-edit.blade.php
@extends('layouts.app')

@section('title', 'Category add')

@section('page-name', 'Category add page')

@section('content')
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <form action="{{ route('category.update', $edit_category->id) }}" method="post" role="form">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" value="{{ $edit_category->name}}" id="name" class="form-control" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/category-list.blade.php
@extends('layouts.app')

@section('title', 'Category list')

@section('page-name', 'Category list')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    All service list
                    <a href="{{ route('category.create') }}" class="btn btn-primary pull-right btn-sm" role="button"
                       style="margin: -5px;">Add new Category</a>
                </div>


                <div class="panel-body" id="sortable">
                    @if(isset($categories) && is_object($categories))
                        <table width="100%" class="table table-striped table-bordered table-hover"
                               id="dataTables-example">
                            <thead>
                            <tr>
                                <th>Id</th>
                                 <th>Name</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr class="odd gradeX">
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td><a href="{{ route('category.edit', $category->id) }}" class="btn btn-info btn-sm"><i class="fa fa-edit fa-fw"></i></a></td>
                                    <td>
                                        <form action="{{ route('category.destroy', $category->id) }}" method="post" onsubmit="return confirm('Are you sure you want to send the service to the trash?')">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash-o fa-fw"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $categories->links() }}
                    @endif
                </div>





















            </div>
        </div>
    </div>

    <div id="load" data-sotr-order-image>
        <i class="fa fa-spinner fa-spin"></i>
    </div>
@endsection

resources/views/admin/feedback-list.blade.php
@extends('layouts.app')

@section('title', 'Feedback')

@section('page-name', 'Feedback page')

@section('content')
<div class="row">
    <div class="col-lg-12">
        {{--@if(count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss></button>
            </div>

        @endif--}}


        @if($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <strong>{{ $message }}</strong>
            </div>
        @endif



            <form action="{{url('/admin/feedback/send')}}" method="post">
                @csrf
                <div class="form-group">
                    <label>Enter Title</label>
                    <input type="text" name="title" class="form-control">
                </div>
                <div class="form-group">
                    <label>Enter Email</label>
                    <input type="text" name="email" class="form-control">
                </div>
                <div class="form-group">
                    <label>Enter Message</label>
                    <textarea name="message" class="form-control"></textarea>
                </div>

                <div class="form-group">
                    <input type="submit" name="send" value="Send" class="btn btn-info">
                </div>

            </form>


    </div>

</div>

@endsection

resources/views/admin/home.blade.php
@extends('layouts.app')

resources/views/admin/news-add.blade.php
@extends('layouts.app')

@section('title', 'News')

@section('page-name', 'News add page')

@section('content')
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <form action="{{ route('news.store') }}" method="post" role="form" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="image">New image</label>
                    <input type="file" name="image" id="image"  class="filestyle" data-buttonBefore="true" data-buttonName="btn-primary">
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" value="{{ old('title') }}" id="title" class="form-control" placeholder="Enter Name">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea class="form-control" name="description" id="description">{{ old('description') }}</textarea>
                </div>
                @if(isset($categories) && is_object($categories))
                    <div class="form-group">
                        <label for="category_id">Enter Category</label>
                        <select name="category_id[]" multiple id="category_id" class="form-control">
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                @endif

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Add News</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script>
        CKEDITOR.replace('text');
    </script>
@endsection

resources/views/admin/news-comment.blade.php
@extends('layouts.app')

@section('title', 'News')

@section('page-name', 'News comment page')

@section('content')
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <form action="{{ route('comment.store', $comment_news->id)}}" method="post">
                @csrf
                <input type="hidden" name="news_id" value="{{ $comment_news->id }}">

                <div class="row">
                    <div class="col-sm-12">
                        <label for="id">Id:</label>
                        {{$comment_news->id}}
                        <br>
                        <label for="title">Title:</label>
                        {{$comment_news->title}}
                        <textarea name="comment" rows="2" class="text-area-messge form-control" placeholder="Enter your comment"></textarea>
                    </div>
                    <div class="col-sm-12">
                        <button class="btn-info" type="submit"><b>POST COMMENT</b></button>
                    </div>
                </div>

            </form>
            <h4><b>Comments({{ $comment_news->comments()->count() }})</b></h4>
            @if($comment_news->comments->count() > 0)
                @foreach($comment_news->comments as $comment)
                    <div class="midtext">
                        <b>{{ $comment->user->name }}</b>
                        <h6>{{ $comment->created_at->diffForHumans() }}</h6>
                    </div>
                    <div class="comment">
                        <p>{{ $comment->comment }}</p>
                        <form action="{{ url('/news/deleteComment',  ['id' => $comment->id]) }}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn-danger">Delete</button>
                        </form>

                    </div>
                    @endforeach
                @else
                <p>No comment yet.</p>
                @endif
        </div>
    </div>





@endsection

resources/views/admin/news-edit.blade.php
@extends('layouts.app')

@section('title', 'News')

@section('page-name', 'News add page')

@section('content')
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <form action="{{ route('news.update', $member_edit->id) }}" method="post" role="form" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <p>Old Image :</p>
                @foreach($member_edit->path as $path)
                    <img src="{{ asset('images') . '/' . $path}}" alt="{{ $path}} " style="width: 100px;height: 100px;">
                    <input type="hidden" name="path" value="{{  $path }}">

                @endforeach
                <div class="form-group">
                    <label for="path">New image</label>
                    <input type="file" name="new_path" id="path"   class="filestyle" data-buttonBefore="true" data-buttonName="btn-primary">
                </div>
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" value="{{ $member_edit->name }}" id="name" class="form-control" placeholder="Enter Name">
                </div>
                <div class="form-group">
                    <label for="facebook_link">Facebook link</label>
                    <input type="url" name="facebook_link" value="{{ $member_edit->facebook_link }}" id="facebook_link" class="form-control" placeholder="Enter link">
                </div>
                <div class="form-group">
                    <label for="twitter_link">Twitter link</label>
                    <input type="url" name="twitter_link" value="{{ $member_edit->twitter_link }}" id="twitter_link" class="form-control" placeholder="Enter link">
                </div>
                <div class="form-group">
                    <label for="gplus_link">Google Plus link</label>
                    <input type="url" name="gplus_link" value="{{ $member_edit->gplus_link }}" id="gplus_link" class="form-control" placeholder="Enter link">
                </div>
                <div class="form-group">
                    <label for="ld_link">Linkedin link</label>
                    <input type="url" name="linkedin_link" value="{{ $member_edit->linkedin_link }}" id="linkedin_link" class="form-control" placeholder="Enter link">
                </div>
                @if(isset($professions) && is_object($professions))
                    <div class="form-group">
                        <label for="profession_id">Enter Category</label>
                        <select name="profession_id" id="profession_id" class="form-control">
                            <option value="">Choose Profession</option>
                            @foreach($professions as $profession)
                                @if( $member_edit->profession_id == $profession->id)
                                    <option value="{{$profession->id}}" selected>{{$profession->name}}</option>

                                @else
                                    <option value="{{$profession->id}}">{{$profession->name}}</option>

                                @endif

                            @endforeach
                        </select>
                    </div>
                @endif

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Edit Member</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script>
        CKEDITOR.replace('text');
    </script>
@endsection

resources/views/admin/news-list.blade.php
@extends('layouts.app')

@section('title', 'News')

@section('page-name', 'News list')
<!--
<<<<<<< HEAD

=======
-->
<!--
>>>>>>> origin/new_branch
-->
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    All News list
                    <a href="{{ route('news.create') }}" class="btn btn-primary pull-right btn-sm" role="button"
                       style="margin: -5px;">Add new News</a>

                    <br><br>


@if(isset($categories))
                            <form action="{{url('/admin/news/findCategory/')}}" method="get">
                                <div class="form-group">
                                    <label>Find category</label>

                                    <div class="form-group">
                                        <label>FROM</label>
                                        <input type="date" name="from" class="form-control">

                                        <label>TO</label>
                                        <input type="date" name="to" class="form-control">

                                    </div>


                                        <select class="form-control" name="role">
                                            @foreach($categories as $category)
                                                @if($category->id == app("request")->input('role'))

                                                    <option selected="selected" value="{{$category->id}}">{{$category->name}}</option>
                                                    @else
                                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                                @endif



                                            @endforeach
                                        </select>

                                </div>
                                <input type="submit" class="btn btn-primary" value="Find" >
                            </form>

                    @endif


                    <br><br>
                   {{-- @if(isset($details))
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Image</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($details as $news)
                                <tr>
                                    <td>{{ $news->title }}</td>
                                    <td>{{ $news->description }}</td>
                                    <td>
                                        <img src="{{asset("images/$news->image")}}" style="width: 100px; height: 100px;">
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                    @endif--}}









                    <form action=" {{url('/admin/news/search')}}" method="get" role="search">
                        <div class="input-group">

                            <input type="text" class="form-control" name="q" placeholder="Search users">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-default">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                        </div>
                    </form>
                    @if(isset($details))
                        <br>
                        Search result:
                    <br><br>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Image</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($details as $user)
                                    <tr>
                                        <td>{{ $user->title }}</td>
                                        <td>{{ $user->description }}</td>
                                        <td>
                                            <img src="{{asset("images/$user->image")}}" style="width: 100px; height: 100px;">
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>
                        @elseif(isset($message))
                        <br>
                        {{ $message }}


                    @endif



                </div>
                <div class="panel-body" id="sortable">
                    @if(isset($news) && is_object($news))
                        <table width="100%" class="table table-striped table-bordered table-hover"
                               id="dataTables-example">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Categories</th>
                                <th>Delete</th>
                                <th>Ffmpeg</th>
                                <th>Like or Dislike</th>
                                <th>Comment</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($news as $item)
                                <tr class="odd gradeX">
                                    <td>{{ $item->id }}</td>
                                    <td>
                                        <img src="{{ asset('images') . '/' . $item->image}}" alt="{{ $item->image}} " style="width: 100px;height: 100px;">
                                    </td>
                                    <td>{{ $item->title }}</td>

                                    <td>

                                {{-- {{str_limit($item->description,10,'') }}
                                        @if(strlen($item->description)>10)
                                            <span id="dots">...</span>
                                            <span id="more">{{ substr($item->description,10) }}</span>
                                        @endif

                                            <button onclick="myFunction()" data-option="{{$item->id}}"  id="myBtn">Read more</button>
--}}
                                        @if(strlen($item->description) > 10)
                                            {{substr($item->description,0,10)}}
                                            <span class="read-more-show">...More</span>
                                            <span class="read-more-content hide_content"> {{substr($item->description,10,strlen($item->description))}}
                                                 <span class="read-more-hide ">Less</span>
                                            </span>
                                        @else
                                            {{$item->description}}
                                        @endif
                                        <style>
                                            .read-more-show{
                                                cursor:pointer;
                                                color: #2e6da4;
                                            }
                                            .read-more-hide{
                                                cursor:pointer;
                                                color: #ed8323;
                                            }

                                            .hide_content{
                                                display: none;
                                            }
                                        </style>


                                      {{--  <style>
                                            #more{
                                                display: none;
                                            }
                                        </style>--}}
                                    </td>

                                    @if(isset( $item->category ))
                                        <td>
                                        @foreach($item->category as $category)
                                            {{$category->name}} <br>
                                        @endforeach
                                        </td>

                                    @else
                                        <td> Null</td>
                                    @endif
                                    <td>
                                        <form action="{{ route('news.destroy', $item->id) }}" method="post" onsubmit="return confirm('Are you sure you want to send the service to the trash?')">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash-o fa-fw"></i></button>
                                        </form>
                                    </td>
                                    <td>
                                        <form action="{{ url('/admin/news/ffmpeg', $item->id) }}" method="post">
                                            @csrf

                                            <button type="submit" class="btn btn-primary btn-sm">Blur</button>
                                        </form>
                                    </td>

                                    <td>
                                        @if(in_array($item->id , $userLikedNews))
<!-- <<<<<<< HEAD

======= -->
                                            <button data-url="{{ route('disLikeNews', ['id' => $item->id]) }}" data-option="dislike" class="like btn btn-danger">Dislike</button>
                                        @else
                                            <button data-url="{{ route('likeNews', ['id' => $item->id]) }}" data-option="like" class="like btn btn-info">Like</button>
                                        @endif

                                    </td>
                                    <td>
                                        <a href="{{ url('/admin/news/commentNews', $item->id) }}"><button type="submit" class="btn-info">Comment</button></a>
<!-- >>>>>>> origin/new_branch -->
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $news->links() }}
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div id="load" data-sotr-order-image>
        <i class="fa fa-spinner fa-spin"></i>
    </div>
@endsection

resources/views/admin/user-edit.blade.php
@extends('layouts.app')

@section('title', 'User edit')

@section('page-name', 'User edit page')

@section('content')
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">



            <form action="/admin/user-update/{{$users->id}}" method="post" role="form">

                @csrf
                <input type="hidden" name="_method" value="PUT">


                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" value="{{$users->name}}" id="name" class="form-control" placeholder="Enter name">
                </div>

                <div class="form-group">
                    <label>Give Role</label>
                    <select name="role" class="form-control">
                        <option value="1">Admin</option>
                        <option value="">None</option>
                    </select>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </form>




        </div>
    </div>

@endsection

resources/views/admin/user-list.blade.php
@extends('layouts.app')

@section('title', 'User list')

@section('page-name', 'User list')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">



                <div class="panel-body" id="sortable">
                    @if(isset($users) && is_object($users))
                        <table width="100%" class="table table-striped table-bordered table-hover"
                               id="dataTables-example">

                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>role</th>
                                <th>Edit</th>

                            </tr>
                            </thead>



                            <tbody>
                            @foreach($users as $row)
                                <tr class="odd gradeX">
                                    <td>{{ $row->id }}</td>
                                    <td>{{ $row->name }}</td>
                                    <td>{{ $row->role }}</td>
                                    <td>
                                        <a href="/admin/user-edit/{{$row->id}}" class="btn btn-info btn-sm"><i class="fa fa-edit fa-fw"></i></a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>



                        </table>
                        {{ $users->links() }}
                    @endif
                </div>





            </div>
        </div>
    </div>

    <div id="load" data-sotr-order-image>
        <i class="fa fa-spinner fa-spin"></i>
    </div>
@endsection